from .domain import (
    Size,
    Dimension,
    TextElement,
    Video,
    VideoProperties,
    VideoSourceType,
    RgbColor,
    Color,
    ThemeColorType,
    SolidFill,
    ShapeBackgroundFill,
    OutlineFill,
    Weight,
    Outline,
    DashStyle,
    ShadowTransform,
    BlurRadius,
    Shadow,
    ShadowType,
    RectanglePosition,
    ShapeProperties,
    CropProperties,
    ColorStop,
    RecolorName,
    Recolor,
    ImageProperties,
    PropertyState,
    StretchedPictureFill,
    PageBackgroundFill,
    AutoText,
    AutoTextType,
    PredefinedLayout,
    ColorScheme,
    ThemeColorPair,
    Line,
    LineProperties,
    WordArt,
    SheetsChart,
    SheetsChartProperties,
    SpeakerSpotlight,
    SpeakerSpotlightProperties,
    Group,
)
from .presentation import Presentation
from .page_all import (
    MasterProperties,
    NotesProperties,
    Page,
    Slide,
    Layout,
    Notes,
    Master,
    NotesMaster,
    LayoutProperties,
    SlideProperties,
)
from .page.base import BasePage, PageProperties, PageType
from .element.base import ElementKind
from .execute import initialize_credentials
